// Command genart authors the ASCII art for the Go port's new plant species and
// writes both the plain .txt and a themed colored .ansi for each growth stage.
// Run from the repo root: `go run ./tools/genart`.
//
// The art bodies below are the source of truth; the .ansi files are generated by
// colorizing each glyph (leaf color by default, an accent color for designated
// runes, and a neutral color for the soil line). Run this whenever the art or
// themes change.
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const (
	green   = "38;5;2"
	red     = "38;5;9"
	yellow  = "38;5;3"
	magenta = "38;5;5"
	blue    = "38;5;4"
	cyan    = "38;5;6"
	white   = "38;5;7"
)

const (
	soil1 = ".  , _ . . _ , _ ., _ ."
	soil2 = "  ^      '   o    `    '"
)

type species struct {
	base        string
	leaf        string
	accent      string
	accentRunes string
	bodies      [3]string // stages 1,2,3 (the art file suffixes 1,2,3)
}

var allSpecies = []species{
	{"bamboo", green, green, "", [3]string{
		`
 |,
 |'
 ||`,
		`
 \|,
  |'
 ,||
  ||
  ||`,
		`
 \|, /|
  |'/ |,
 ,||  |'
  ||  ||
  || ,||
  ||  ||`,
	}},
	{"rose", green, red, "@&*", [3]string{
		`
  *
  |
 \|`,
		`
 (@)
  |
 \|/
  |`,
		`
 @ @ @
  \|/
 (@)|
  \|/
   |
  /|`,
	}},
	{"orchid", green, magenta, "*o@", [3]string{
		`
  o
  |
  |`,
		`
 *o*
  |
  |\
  |`,
		`
*o* *o*
  \ /
 *o|
   |\
   | \
   |`,
	}},
	{"mushroom", red, white, "|", [3]string{
		`
 .-.
 | |`,
		`
 .-=-.
 (___)
  | |
  | |`,
		`
 .-===-.
(_______)
  |   |
  | . |
 _|___|_`,
	}},
	{"ivy", green, green, "", [3]string{
		`
 ,
 %,
  %`,
		`
  ,%
 %,
  ,%
 %,`,
		`
 %, ,%
  ,%,
 %, ,%
  ,%,
 %, ,%
  %`,
	}},
	{"lavender", green, magenta, "*", [3]string{
		`
 *
 |
 |`,
		`
 * *
 | |
 \|/
  |`,
		`
* * * *
| | | |
\ \|/ /
 \|||/
  |||`,
	}},
	{"maple", green, yellow, "|", [3]string{
		`
 ^
 |`,
		`
 ^^^
 \|/
  |
  |`,
		`
 ^^^^^
^^^^^^^
 \\|//
   |
   |
   |`,
	}},
	{"pitcher", green, red, ".", [3]string{
		`
 \_/
 |.|`,
		`
  __
 /  \
 |..|
 |  |
 \__/`,
		`
 _  __
/ \/  \
|.||..|
| ||  |
\_/\__/`,
	}},
	{"sundew", green, red, "o", [3]string{
		`
 o o
  \|`,
		`
o o o
 \|/
 -+-
  |`,
		`
o o o o
 \\|//
o-+++-o
  \|/
   |`,
	}},
	{"waterlily", green, magenta, "@o*", [3]string{
		`
 __
(__)`,
		`
  o
 (@)
(____)
~~~~~~`,
		`
 @ o @
 \(@)/
(______)
~~~~~~~~`,
	}},
	{"kelp", cyan, cyan, "", [3]string{
		`
 (
 )
 (`,
		`
 ((
 ))
 ((
 ))`,
		`
 ( )
 ) (
 ( )
 ) (
 ( )
 \|/`,
	}},
	{"tulip", green, red, "U", [3]string{
		`
 \./
  |`,
		`
 \U/
  |
 \|
  |`,
		`
\U/ \U/
 |   |
 \\ //
  \|/
   |`,
	}},
	{"morningglory", green, blue, "@o*", [3]string{
		`
 @
 \
 |`,
		`
 @ o
  \|
  /|
 |`,
		`
@  o  @
 \ | /
 o-+-@
   |\
   | \`,
	}},
}

// pad lays the plant body over a fixed 10-line canvas with the soil at the
// bottom, so every species' soil line lands on the same row.
func pad(body string) []string {
	bodyLines := strings.Split(strings.Trim(body, "\n"), "\n")
	const total = 10
	n := total - len(bodyLines) - 2
	if n < 0 {
		n = 0
	}
	lines := make([]string, n)
	lines = append(lines, bodyLines...)
	lines = append(lines, soil1, soil2)
	return lines
}

func colorize(lines []string, leaf, accent, accentRunes string) string {
	var out strings.Builder
	for i, line := range lines {
		isSoil := i >= len(lines)-2
		for _, r := range line {
			if r == ' ' {
				out.WriteByte(' ')
				continue
			}
			color := leaf
			switch {
			case isSoil:
				color = white
			case strings.ContainsRune(accentRunes, r):
				color = accent
			}
			out.WriteString("\x1b[")
			out.WriteString(color)
			out.WriteByte('m')
			out.WriteRune(r)
		}
		out.WriteByte('\n')
	}
	return out.String()
}

func main() {
	artDir := "art"
	if len(os.Args) > 1 {
		artDir = os.Args[1]
	}
	count := 0
	for _, sp := range allSpecies {
		for i, body := range sp.bodies {
			lines := pad(body)
			stage := fmt.Sprintf("%d", i+1)

			txtPath := filepath.Join(artDir, sp.base+stage+".txt")
			if err := os.WriteFile(txtPath, []byte(strings.Join(lines, "\n")+"\n"), 0o644); err != nil {
				panic(err)
			}

			ansiPath := filepath.Join(artDir, sp.base+stage+".ansi")
			if err := os.WriteFile(ansiPath, []byte(colorize(lines, sp.leaf, sp.accent, sp.accentRunes)), 0o644); err != nil {
				panic(err)
			}
			count += 2
		}
	}
	fmt.Printf("wrote %d art files for %d species to %s\n", count, len(allSpecies), artDir)
}
